add_newline = false

[battery]
full_symbol = "🔋"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[package]
disabled = true

[cmd_duration]
style = "bold blue"
